package com.chattriggers.ctjs.api.render

import com.mojang.blaze3d.pipeline.RenderPipeline
import net.minecraft.client.gl.RenderPipelines

enum class RenderSnippet(val mcSnippet: RenderPipeline.Snippet) {
    //#if MC<=12105
    MATRICES_SNIPPET(RenderPipelines.MATRICES_SNIPPET),
    FOG_NO_COLOR_SNIPPET(RenderPipelines.FOG_NO_COLOR_SNIPPET),
    FOG_SNIPPET(RenderPipelines.FOG_SNIPPET),
    MATRICES_COLOR_SNIPPET(RenderPipelines.MATRICES_COLOR_SNIPPET),
    MATRICES_COLOR_FOG_SNIPPET(RenderPipelines.MATRICES_COLOR_FOG_SNIPPET),
    MATRICES_COLOR_FOG_OFFSET_SNIPPET(RenderPipelines.MATRICES_COLOR_FOG_OFFSET_SNIPPET),
    MATRICES_COLOR_FOG_LIGHT_DIR_SNIPPET(RenderPipelines.MATRICES_COLOR_FOG_LIGHT_DIR_SNIPPET),
    //#endif

    TERRAIN_SNIPPET(RenderPipelines.TERRAIN_SNIPPET),
    ENTITY_SNIPPET(RenderPipelines.ENTITY_SNIPPET),
    RENDERTYPE_BEACON_BEAM_SNIPPET(RenderPipelines.RENDERTYPE_BEACON_BEAM_SNIPPET),
    TEXT_SNIPPET(RenderPipelines.TEXT_SNIPPET),
    RENDERTYPE_END_PORTAL_SNIPPET(RenderPipelines.RENDERTYPE_END_PORTAL_SNIPPET),
    RENDERTYPE_CLOUDS_SNIPPET(RenderPipelines.RENDERTYPE_CLOUDS_SNIPPET),
    RENDERTYPE_LINES_SNIPPET(RenderPipelines.RENDERTYPE_LINES_SNIPPET),
    POSITION_COLOR_SNIPPET(RenderPipelines.POSITION_COLOR_SNIPPET),
    PARTICLE_SNIPPET(RenderPipelines.PARTICLE_SNIPPET),
    WEATHER_SNIPPET(RenderPipelines.WEATHER_SNIPPET),
    GUI_SNIPPET(RenderPipelines.GUI_SNIPPET),
    POSITION_TEX_COLOR_SNIPPET(RenderPipelines.POSITION_TEX_COLOR_SNIPPET),
    RENDERTYPE_OUTLINE_SNIPPET(RenderPipelines.RENDERTYPE_OUTLINE_SNIPPET),
    POST_EFFECT_PROCESSOR_SNIPPET(RenderPipelines.POST_EFFECT_PROCESSOR_SNIPPET),
}
